### ISSUE TITLE
what are the useful infos?

### ISSUE THREAD

**Issue by Kosta-Github** [lazywithclass/swaggins#3]
What are the useful infos you are referring to by this: `Swaggins extracts useful information for your Swagger docs from Node.js HTTP res object.`

**Comment by lazywithclass** [comment]
Wow, first person to open an issue here, welcome! :D

Here is a list
- `path` of the endpoint
- `method`(s) that the endpoint supports
- `statusCode` returned by the call to the endpoint
- `body` either passed to the endpoint (via POST) for example, or received from the endpoint

and something else that I'm surely missing. On top of that you could add custom descriptions and endpoints name for the Swagger docs, for things like for example `/api/1/questions/{question-id}`.

@Kosta-Github Would you need something else there?

I will be adding a section to the README in which I clearly specify all of this, thanks for the feedback!

**Comment by Kosta-Github** [comment]
ok, maybe I missed that, but I assumed you were augmenting an existing `swagger` spec file with additional fields, but now it looks like you are creating a complete `swagger` spec file based on the integration test requests and their responses?

**Comment by lazywithclass** [comment]
If you missed it it means it's not clear in the docs, so I will try to make it more understandable.

What swaggins does is basically look at the HTTP `res` while it's passing back and forward between integration tests and extract the info I've listed above. With that info then goes to populate a Swagger spec file, or augment it if it's already there... (because `path`, `method`, `statusCode` form a sort of unique identifier).

**Comment by lazywithclass** [comment]
@Kosta-Github I've extended the README, I will be adding some more routes to the example so to provide a better idea of what the tool can do; please let me know if there's something missing there, be it features or more documentation around them.
